llm:
  temperature: 0.7
  max_tokens: 2048
  timeout: 30

chains:
  grammar:
    confidence_threshold: 0.8
    max_corrections: 5
  vocabulary:
    suggestions_count: 3
    context_window: 5
  response:
    max_length: 1000
    style: educational


model: gpt-4
provider: openAI